---
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  hosts:
    server:
      ansible_host: 192.168.100.102
  children:
    metal:
      children:
        proxmox:
          hosts:
            server:
