---
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  hosts:
    server:
      ansible_host: 192.168.1.102
      mac: "bc:30:5b:eb:96:df"
      bmc:
        ip: 192.168.1.120
        user: root
        password: root
      language: en
      country: FR
      locale: en_US.UTF-8
      keyboard: fr(latin9)
  children:
    metal:
      children:
        ipmi:
          hosts:
            server:
