---
all:
  hosts:
    server:
      ansible_host: 192.168.1.102
      mac: "bc:30:5b:eb:96:df"
      bmc:
        ip: 192.168.1.120
        user: root
        password: root
  children:
    metal:
      children:
        ipmi:
          hosts:
            server:
