---
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  hosts:
    server:
      ansible_host: 192.168.1.102
      mac: "bc:30:5b:eb:96:df"
      interface: enp0s1
      bios: legacy
      bmc:
        ip: 192.168.1.120
        user: root
        password: root
      disks:
        boot:
          serial_number: ""
      language: en
      country: FR
      locale: en_US.UTF-8
      keyboard: fr(latin9)
    nas:
      ansible_host: 192.168.1.103
      mac: "d0:50:99:d1:91:22"
      interface: enp4s0
      bios: legacy
      bmc:
        ip: 192.168.1.54
        user: admin
        password: admin
      disks:
        boot:
          serial_number: 134D53BB
      language: en
      country: FR
      locale: en_US.UTF-8
      keyboard: fr(latin9)
  children:
    metal:
      children:
        ipmi:
          hosts:
            server:
            nas:
        proxmox:
          hosts:
            nas:
