---
- name: create pxe server directories
  file:
    path: "{{lookup('vars', 'pxe_server_' + item + '_path')}}"
    recurse: true
    state: directory
  loop:
    - "target"
    - "config"
    - "iso"
    - "log"
    - "os"

- name: download network boot image
  vars:
    iso_url: "{{pxe_server_boot_image_url}}"
  get_url:
    url: "{{iso_url}}"
    dest: "{{pxe_server_iso_path}}/{{iso_url | basename}}"
    checksum: "{{pxe_server_boot_image_checksum}}"

- name: unarchive network boot image
  unarchive:
    src: "{{pxe_server_iso_path}}/{{pxe_server_boot_image_url | basename}}"
    dest: "{{pxe_server_os_path}}"

- name: download syslinux package
  get_url:
    url: "{{pxe_server_syslinux_url}}"
    dest: "{{pxe_server_target_path}}"
    checksum: "{{pxe_server_syslinux_checksum}}"

- name: unarchive syslinux package
  unarchive:
    src: "{{pxe_server_target_path}}/{{pxe_server_syslinux_package}}"
    dest: "{{pxe_server_target_path}}"

- name: copy pxe bootloader
  copy:
    src: "{{pxe_server_target_path}}/{{pxe_server_syslinux_package_name}}/bios/core/lpxelinux.0"
    dest: "{{pxe_server_os_path}}/debian-installer/amd64/lpxelinux.0"

- name: create symbolic link to pxe bootloader
  file:
    src: "debian-installer/amd64/lpxelinux.0"
    dest: "{{pxe_server_os_path}}/lpxelinux.0"
    state: link

- name: render pxe menu configuration
  template:
    src: "menu.cfg.j2"
    dest: "{{pxe_server_os_path}}/debian-installer/amd64/boot-screens/menu.cfg"
    backup: true

- name: render dnsmasq configuration
  template:
    src: "dnsmasq.conf.j2"
    dest: "{{pxe_server_config_path}}/dnsmasq.conf"
  register: dnsmasq_config

- name: ensure dnsmasq log file exists
  file:
    path: "{{pxe_server_log_path}}/dnsmasq.log"
    state: touch

- name: start dnsmasq container
  docker_container:
    name: homelab-pxe-dnsmasq
    image: andyshinn/dnsmasq
    pull: true
    #auto_remove: true
    network_mode: host
    state: started
    restart: "{{dnsmasq_config.changed}}"
    command:
      - "--no-daemon"
      - "--conf-file=/opt/dnsmasq.conf"
      - "--dhcp-broadcast"
    capabilities:
      - net_admin
    volumes:
      - "{{pxe_server_config_path}}/dnsmasq.conf:/opt/dnsmasq.conf"
      - "{{pxe_server_os_path}}:/srv/tftp"
      - "{{pxe_server_log_path}}/dnsmasq.log:/var/log/dnsmasq.log"

- name: start nginx container
  docker_container:
    name: homelab-pxe-nginx
    image: nginx:alpine
    pull: true
    #auto_remove: true
    network_mode: host
    state: started
    volumes:
      - "{{pxe_server_os_path}}:/usr/share/nginx/html"
